/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#f9f9ff",
        surface: "#f9f9ff",
        "surface-bright": "#f9f9ff",
        "surface-dim": "#d3daea",
        "surface-variant": "#dce2f3",
        "surface-container": "#e7eefe",
        "surface-container-low": "#f0f3ff",
        "surface-container-high": "#e2e8f8",
        "surface-container-highest": "#dce2f3",
        "surface-container-lowest": "#ffffff",
        primary: "#154212",
        "primary-container": "#2d5a27",
        "on-primary": "#ffffff",
        "on-primary-container": "#9dd090",
        "inverse-primary": "#a1d494",
        "primary-fixed": "#bcf0ae",
        "primary-fixed-dim": "#a1d494",
        "on-primary-fixed": "#002201",
        "on-primary-fixed-variant": "#23501e",
        secondary: "#4b635c",
        "on-secondary": "#ffffff",
      "secondary-container": "#cbe5dc",
        "on-secondary-container": "#4f6860",
        "secondary-fixed": "#cee8df",
        "secondary-fixed-dim": "#b2ccc3",
        "on-secondary-fixed": "#071f1a",
        "on-secondary-fixed-variant": "#344b45",
        tertiary: "#60233e",
        "on-tertiary": "#ffffff",
      "tertiary-container": "#7c3a55",
        "tertiary-fixed": "#ffd9e4",
        "tertiary-fixed-dim": "#ffb0cc",
        "on-tertiary-fixed": "#3b0520",
        "on-tertiary-fixed-variant": "#71314c",
        "on-tertiary-container": "#ffaac8",
        "on-background": "#151c27",
        "on-surface": "#151c27",
        "on-surface-variant": "#42493e",
        outline: "#72796e",
        "outline-variant": "#c2c9bb",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-surface": "#2a313d",
        "inverse-on-surface": "#ebf1ff",
        "surface-tint": "#3b6934",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "8px",
        margin: "32px",
        gutter: "24px",
        sidebar: "260px",
      },
      maxWidth: {
        container: "1440px",
      },
      fontFamily: {
        sans: ["Inter", "PingFang SC", "Microsoft YaHei", "sans-serif"],
        "body-md": ["Inter", "PingFang SC", "Microsoft YaHei", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
        "mono-data": ["JetBrains Mono", "ui-monospace", "monospace"],
        label: ["Inter", "PingFang SC", "Microsoft YaHei", "sans-serif"],
        h1: ["Inter", "PingFang SC", "Microsoft YaHei", "sans-serif"],
        h2: ["Inter", "PingFang SC", "Microsoft YaHei", "sans-serif"],
        h3: ["Inter", "PingFang SC", "Microsoft YaHei", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        h2: ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        h3: ["20px", { lineHeight: "28px", fontWeight: "600" }],
        h1: ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "mono-data": ["13px", { lineHeight: "18px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
